language: python
python:
  - "2.7"

install:
  - pip install flask
  
before_script:
  - nohup python flask-ip.py & 
  
script:
  - ifconfig
  - curl http://localhost:5000/
  - curl http://localhost:5000/get_my_ip
